/*
mailcow API

Testing LogsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mailcowsdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_mailcowsdk_LogsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test LogsAPIService GetACMELogs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var count float32

		httpRes, err := apiClient.LogsAPI.GetACMELogs(context.Background(), count).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LogsAPIService GetApiLogs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var count float32

		httpRes, err := apiClient.LogsAPI.GetApiLogs(context.Background(), count).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LogsAPIService GetAutodiscoverLogs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var count float32

		httpRes, err := apiClient.LogsAPI.GetAutodiscoverLogs(context.Background(), count).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LogsAPIService GetDovecotLogs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var count float32

		httpRes, err := apiClient.LogsAPI.GetDovecotLogs(context.Background(), count).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LogsAPIService GetNetfilterLogs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var count float32

		httpRes, err := apiClient.LogsAPI.GetNetfilterLogs(context.Background(), count).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LogsAPIService GetPostfixLogs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var count float32

		httpRes, err := apiClient.LogsAPI.GetPostfixLogs(context.Background(), count).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LogsAPIService GetRatelimitLogs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var count float32

		httpRes, err := apiClient.LogsAPI.GetRatelimitLogs(context.Background(), count).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LogsAPIService GetRspamdLogs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var count float32

		httpRes, err := apiClient.LogsAPI.GetRspamdLogs(context.Background(), count).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LogsAPIService GetSOGoLogs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var count float32

		httpRes, err := apiClient.LogsAPI.GetSOGoLogs(context.Background(), count).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LogsAPIService GetWatchdogLogs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var count float32

		httpRes, err := apiClient.LogsAPI.GetWatchdogLogs(context.Background(), count).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
