/*
mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailcowsdk

import (
	"encoding/json"
)

// checks if the UpdateDomainWideFooterRequestAttr type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDomainWideFooterRequestAttr{}

// UpdateDomainWideFooterRequestAttr struct for UpdateDomainWideFooterRequestAttr
type UpdateDomainWideFooterRequestAttr struct {
	// Footer text in HTML format
	Html *string `json:"html,omitempty"`
	// Footer text in PLAIN text format
	Plain *string `json:"plain,omitempty"`
	// Array of mailboxes to exclude from domain wide footer
	MboxExclude map[string]interface{} `json:"mbox_exclude,omitempty"`
}

// NewUpdateDomainWideFooterRequestAttr instantiates a new UpdateDomainWideFooterRequestAttr object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDomainWideFooterRequestAttr() *UpdateDomainWideFooterRequestAttr {
	this := UpdateDomainWideFooterRequestAttr{}
	return &this
}

// NewUpdateDomainWideFooterRequestAttrWithDefaults instantiates a new UpdateDomainWideFooterRequestAttr object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDomainWideFooterRequestAttrWithDefaults() *UpdateDomainWideFooterRequestAttr {
	this := UpdateDomainWideFooterRequestAttr{}
	return &this
}

// GetHtml returns the Html field value if set, zero value otherwise.
func (o *UpdateDomainWideFooterRequestAttr) GetHtml() string {
	if o == nil || IsNil(o.Html) {
		var ret string
		return ret
	}
	return *o.Html
}

// GetHtmlOk returns a tuple with the Html field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDomainWideFooterRequestAttr) GetHtmlOk() (*string, bool) {
	if o == nil || IsNil(o.Html) {
		return nil, false
	}
	return o.Html, true
}

// HasHtml returns a boolean if a field has been set.
func (o *UpdateDomainWideFooterRequestAttr) HasHtml() bool {
	if o != nil && !IsNil(o.Html) {
		return true
	}

	return false
}

// SetHtml gets a reference to the given string and assigns it to the Html field.
func (o *UpdateDomainWideFooterRequestAttr) SetHtml(v string) {
	o.Html = &v
}

// GetPlain returns the Plain field value if set, zero value otherwise.
func (o *UpdateDomainWideFooterRequestAttr) GetPlain() string {
	if o == nil || IsNil(o.Plain) {
		var ret string
		return ret
	}
	return *o.Plain
}

// GetPlainOk returns a tuple with the Plain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDomainWideFooterRequestAttr) GetPlainOk() (*string, bool) {
	if o == nil || IsNil(o.Plain) {
		return nil, false
	}
	return o.Plain, true
}

// HasPlain returns a boolean if a field has been set.
func (o *UpdateDomainWideFooterRequestAttr) HasPlain() bool {
	if o != nil && !IsNil(o.Plain) {
		return true
	}

	return false
}

// SetPlain gets a reference to the given string and assigns it to the Plain field.
func (o *UpdateDomainWideFooterRequestAttr) SetPlain(v string) {
	o.Plain = &v
}

// GetMboxExclude returns the MboxExclude field value if set, zero value otherwise.
func (o *UpdateDomainWideFooterRequestAttr) GetMboxExclude() map[string]interface{} {
	if o == nil || IsNil(o.MboxExclude) {
		var ret map[string]interface{}
		return ret
	}
	return o.MboxExclude
}

// GetMboxExcludeOk returns a tuple with the MboxExclude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDomainWideFooterRequestAttr) GetMboxExcludeOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.MboxExclude) {
		return map[string]interface{}{}, false
	}
	return o.MboxExclude, true
}

// HasMboxExclude returns a boolean if a field has been set.
func (o *UpdateDomainWideFooterRequestAttr) HasMboxExclude() bool {
	if o != nil && !IsNil(o.MboxExclude) {
		return true
	}

	return false
}

// SetMboxExclude gets a reference to the given map[string]interface{} and assigns it to the MboxExclude field.
func (o *UpdateDomainWideFooterRequestAttr) SetMboxExclude(v map[string]interface{}) {
	o.MboxExclude = v
}

func (o UpdateDomainWideFooterRequestAttr) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDomainWideFooterRequestAttr) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Html) {
		toSerialize["html"] = o.Html
	}
	if !IsNil(o.Plain) {
		toSerialize["plain"] = o.Plain
	}
	if !IsNil(o.MboxExclude) {
		toSerialize["mbox_exclude"] = o.MboxExclude
	}
	return toSerialize, nil
}

type NullableUpdateDomainWideFooterRequestAttr struct {
	value *UpdateDomainWideFooterRequestAttr
	isSet bool
}

func (v NullableUpdateDomainWideFooterRequestAttr) Get() *UpdateDomainWideFooterRequestAttr {
	return v.value
}

func (v *NullableUpdateDomainWideFooterRequestAttr) Set(val *UpdateDomainWideFooterRequestAttr) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDomainWideFooterRequestAttr) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDomainWideFooterRequestAttr) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDomainWideFooterRequestAttr(val *UpdateDomainWideFooterRequestAttr) *NullableUpdateDomainWideFooterRequestAttr {
	return &NullableUpdateDomainWideFooterRequestAttr{value: val, isSet: true}
}

func (v NullableUpdateDomainWideFooterRequestAttr) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDomainWideFooterRequestAttr) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


