/*
mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailcowsdk

import (
	"encoding/json"
)

// checks if the UpdateDomainWideFooterRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDomainWideFooterRequest{}

// UpdateDomainWideFooterRequest struct for UpdateDomainWideFooterRequest
type UpdateDomainWideFooterRequest struct {
	Attr *UpdateDomainWideFooterRequestAttr `json:"attr,omitempty"`
	// contains a list of domain names where you want to update the footer
	Items []string `json:"items,omitempty"`
}

// NewUpdateDomainWideFooterRequest instantiates a new UpdateDomainWideFooterRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDomainWideFooterRequest() *UpdateDomainWideFooterRequest {
	this := UpdateDomainWideFooterRequest{}
	return &this
}

// NewUpdateDomainWideFooterRequestWithDefaults instantiates a new UpdateDomainWideFooterRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDomainWideFooterRequestWithDefaults() *UpdateDomainWideFooterRequest {
	this := UpdateDomainWideFooterRequest{}
	return &this
}

// GetAttr returns the Attr field value if set, zero value otherwise.
func (o *UpdateDomainWideFooterRequest) GetAttr() UpdateDomainWideFooterRequestAttr {
	if o == nil || IsNil(o.Attr) {
		var ret UpdateDomainWideFooterRequestAttr
		return ret
	}
	return *o.Attr
}

// GetAttrOk returns a tuple with the Attr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDomainWideFooterRequest) GetAttrOk() (*UpdateDomainWideFooterRequestAttr, bool) {
	if o == nil || IsNil(o.Attr) {
		return nil, false
	}
	return o.Attr, true
}

// HasAttr returns a boolean if a field has been set.
func (o *UpdateDomainWideFooterRequest) HasAttr() bool {
	if o != nil && !IsNil(o.Attr) {
		return true
	}

	return false
}

// SetAttr gets a reference to the given UpdateDomainWideFooterRequestAttr and assigns it to the Attr field.
func (o *UpdateDomainWideFooterRequest) SetAttr(v UpdateDomainWideFooterRequestAttr) {
	o.Attr = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *UpdateDomainWideFooterRequest) GetItems() []string {
	if o == nil || IsNil(o.Items) {
		var ret []string
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDomainWideFooterRequest) GetItemsOk() ([]string, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *UpdateDomainWideFooterRequest) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []string and assigns it to the Items field.
func (o *UpdateDomainWideFooterRequest) SetItems(v []string) {
	o.Items = v
}

func (o UpdateDomainWideFooterRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDomainWideFooterRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Attr) {
		toSerialize["attr"] = o.Attr
	}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableUpdateDomainWideFooterRequest struct {
	value *UpdateDomainWideFooterRequest
	isSet bool
}

func (v NullableUpdateDomainWideFooterRequest) Get() *UpdateDomainWideFooterRequest {
	return v.value
}

func (v *NullableUpdateDomainWideFooterRequest) Set(val *UpdateDomainWideFooterRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDomainWideFooterRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDomainWideFooterRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDomainWideFooterRequest(val *UpdateDomainWideFooterRequest) *NullableUpdateDomainWideFooterRequest {
	return &NullableUpdateDomainWideFooterRequest{value: val, isSet: true}
}

func (v NullableUpdateDomainWideFooterRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDomainWideFooterRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


