/*
mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailcowsdk

import (
	"encoding/json"
)

// checks if the EditCrossOriginResourceSharingCORSSettingsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditCrossOriginResourceSharingCORSSettingsRequest{}

// EditCrossOriginResourceSharingCORSSettingsRequest struct for EditCrossOriginResourceSharingCORSSettingsRequest
type EditCrossOriginResourceSharingCORSSettingsRequest struct {
	Attr *EditCrossOriginResourceSharingCORSSettingsRequestAttr `json:"attr,omitempty"`
}

// NewEditCrossOriginResourceSharingCORSSettingsRequest instantiates a new EditCrossOriginResourceSharingCORSSettingsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditCrossOriginResourceSharingCORSSettingsRequest() *EditCrossOriginResourceSharingCORSSettingsRequest {
	this := EditCrossOriginResourceSharingCORSSettingsRequest{}
	return &this
}

// NewEditCrossOriginResourceSharingCORSSettingsRequestWithDefaults instantiates a new EditCrossOriginResourceSharingCORSSettingsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditCrossOriginResourceSharingCORSSettingsRequestWithDefaults() *EditCrossOriginResourceSharingCORSSettingsRequest {
	this := EditCrossOriginResourceSharingCORSSettingsRequest{}
	return &this
}

// GetAttr returns the Attr field value if set, zero value otherwise.
func (o *EditCrossOriginResourceSharingCORSSettingsRequest) GetAttr() EditCrossOriginResourceSharingCORSSettingsRequestAttr {
	if o == nil || IsNil(o.Attr) {
		var ret EditCrossOriginResourceSharingCORSSettingsRequestAttr
		return ret
	}
	return *o.Attr
}

// GetAttrOk returns a tuple with the Attr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditCrossOriginResourceSharingCORSSettingsRequest) GetAttrOk() (*EditCrossOriginResourceSharingCORSSettingsRequestAttr, bool) {
	if o == nil || IsNil(o.Attr) {
		return nil, false
	}
	return o.Attr, true
}

// HasAttr returns a boolean if a field has been set.
func (o *EditCrossOriginResourceSharingCORSSettingsRequest) HasAttr() bool {
	if o != nil && !IsNil(o.Attr) {
		return true
	}

	return false
}

// SetAttr gets a reference to the given EditCrossOriginResourceSharingCORSSettingsRequestAttr and assigns it to the Attr field.
func (o *EditCrossOriginResourceSharingCORSSettingsRequest) SetAttr(v EditCrossOriginResourceSharingCORSSettingsRequestAttr) {
	o.Attr = &v
}

func (o EditCrossOriginResourceSharingCORSSettingsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditCrossOriginResourceSharingCORSSettingsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Attr) {
		toSerialize["attr"] = o.Attr
	}
	return toSerialize, nil
}

type NullableEditCrossOriginResourceSharingCORSSettingsRequest struct {
	value *EditCrossOriginResourceSharingCORSSettingsRequest
	isSet bool
}

func (v NullableEditCrossOriginResourceSharingCORSSettingsRequest) Get() *EditCrossOriginResourceSharingCORSSettingsRequest {
	return v.value
}

func (v *NullableEditCrossOriginResourceSharingCORSSettingsRequest) Set(val *EditCrossOriginResourceSharingCORSSettingsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEditCrossOriginResourceSharingCORSSettingsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEditCrossOriginResourceSharingCORSSettingsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditCrossOriginResourceSharingCORSSettingsRequest(val *EditCrossOriginResourceSharingCORSSettingsRequest) *NullableEditCrossOriginResourceSharingCORSSettingsRequest {
	return &NullableEditCrossOriginResourceSharingCORSSettingsRequest{value: val, isSet: true}
}

func (v NullableEditCrossOriginResourceSharingCORSSettingsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditCrossOriginResourceSharingCORSSettingsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


