/*
mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailcowsdk

import (
	"encoding/json"
)

// checks if the UpdateMailboxCustomAttributesRequestAttr type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateMailboxCustomAttributesRequestAttr{}

// UpdateMailboxCustomAttributesRequestAttr struct for UpdateMailboxCustomAttributesRequestAttr
type UpdateMailboxCustomAttributesRequestAttr struct {
	// Array of attribute keys
	Attribute map[string]interface{} `json:"attribute,omitempty"`
	// Array of attribute values
	Value map[string]interface{} `json:"value,omitempty"`
}

// NewUpdateMailboxCustomAttributesRequestAttr instantiates a new UpdateMailboxCustomAttributesRequestAttr object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateMailboxCustomAttributesRequestAttr() *UpdateMailboxCustomAttributesRequestAttr {
	this := UpdateMailboxCustomAttributesRequestAttr{}
	return &this
}

// NewUpdateMailboxCustomAttributesRequestAttrWithDefaults instantiates a new UpdateMailboxCustomAttributesRequestAttr object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateMailboxCustomAttributesRequestAttrWithDefaults() *UpdateMailboxCustomAttributesRequestAttr {
	this := UpdateMailboxCustomAttributesRequestAttr{}
	return &this
}

// GetAttribute returns the Attribute field value if set, zero value otherwise.
func (o *UpdateMailboxCustomAttributesRequestAttr) GetAttribute() map[string]interface{} {
	if o == nil || IsNil(o.Attribute) {
		var ret map[string]interface{}
		return ret
	}
	return o.Attribute
}

// GetAttributeOk returns a tuple with the Attribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateMailboxCustomAttributesRequestAttr) GetAttributeOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Attribute) {
		return map[string]interface{}{}, false
	}
	return o.Attribute, true
}

// HasAttribute returns a boolean if a field has been set.
func (o *UpdateMailboxCustomAttributesRequestAttr) HasAttribute() bool {
	if o != nil && !IsNil(o.Attribute) {
		return true
	}

	return false
}

// SetAttribute gets a reference to the given map[string]interface{} and assigns it to the Attribute field.
func (o *UpdateMailboxCustomAttributesRequestAttr) SetAttribute(v map[string]interface{}) {
	o.Attribute = v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *UpdateMailboxCustomAttributesRequestAttr) GetValue() map[string]interface{} {
	if o == nil || IsNil(o.Value) {
		var ret map[string]interface{}
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateMailboxCustomAttributesRequestAttr) GetValueOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return map[string]interface{}{}, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *UpdateMailboxCustomAttributesRequestAttr) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given map[string]interface{} and assigns it to the Value field.
func (o *UpdateMailboxCustomAttributesRequestAttr) SetValue(v map[string]interface{}) {
	o.Value = v
}

func (o UpdateMailboxCustomAttributesRequestAttr) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateMailboxCustomAttributesRequestAttr) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Attribute) {
		toSerialize["attribute"] = o.Attribute
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableUpdateMailboxCustomAttributesRequestAttr struct {
	value *UpdateMailboxCustomAttributesRequestAttr
	isSet bool
}

func (v NullableUpdateMailboxCustomAttributesRequestAttr) Get() *UpdateMailboxCustomAttributesRequestAttr {
	return v.value
}

func (v *NullableUpdateMailboxCustomAttributesRequestAttr) Set(val *UpdateMailboxCustomAttributesRequestAttr) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateMailboxCustomAttributesRequestAttr) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateMailboxCustomAttributesRequestAttr) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateMailboxCustomAttributesRequestAttr(val *UpdateMailboxCustomAttributesRequestAttr) *NullableUpdateMailboxCustomAttributesRequestAttr {
	return &NullableUpdateMailboxCustomAttributesRequestAttr{value: val, isSet: true}
}

func (v NullableUpdateMailboxCustomAttributesRequestAttr) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateMailboxCustomAttributesRequestAttr) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


