/*
mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailcowsdk

import (
	"encoding/json"
)

// checks if the EditExternalIdentityProviderSettingsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditExternalIdentityProviderSettingsRequest{}

// EditExternalIdentityProviderSettingsRequest struct for EditExternalIdentityProviderSettingsRequest
type EditExternalIdentityProviderSettingsRequest struct {
	Items []interface{} `json:"items,omitempty"`
	Attr *EditExternalIdentityProviderSettingsRequestAttr `json:"attr,omitempty"`
}

// NewEditExternalIdentityProviderSettingsRequest instantiates a new EditExternalIdentityProviderSettingsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditExternalIdentityProviderSettingsRequest() *EditExternalIdentityProviderSettingsRequest {
	this := EditExternalIdentityProviderSettingsRequest{}
	return &this
}

// NewEditExternalIdentityProviderSettingsRequestWithDefaults instantiates a new EditExternalIdentityProviderSettingsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditExternalIdentityProviderSettingsRequestWithDefaults() *EditExternalIdentityProviderSettingsRequest {
	this := EditExternalIdentityProviderSettingsRequest{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequest) GetItems() []interface{} {
	if o == nil || IsNil(o.Items) {
		var ret []interface{}
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequest) GetItemsOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequest) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []interface{} and assigns it to the Items field.
func (o *EditExternalIdentityProviderSettingsRequest) SetItems(v []interface{}) {
	o.Items = v
}

// GetAttr returns the Attr field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequest) GetAttr() EditExternalIdentityProviderSettingsRequestAttr {
	if o == nil || IsNil(o.Attr) {
		var ret EditExternalIdentityProviderSettingsRequestAttr
		return ret
	}
	return *o.Attr
}

// GetAttrOk returns a tuple with the Attr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequest) GetAttrOk() (*EditExternalIdentityProviderSettingsRequestAttr, bool) {
	if o == nil || IsNil(o.Attr) {
		return nil, false
	}
	return o.Attr, true
}

// HasAttr returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequest) HasAttr() bool {
	if o != nil && !IsNil(o.Attr) {
		return true
	}

	return false
}

// SetAttr gets a reference to the given EditExternalIdentityProviderSettingsRequestAttr and assigns it to the Attr field.
func (o *EditExternalIdentityProviderSettingsRequest) SetAttr(v EditExternalIdentityProviderSettingsRequestAttr) {
	o.Attr = &v
}

func (o EditExternalIdentityProviderSettingsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditExternalIdentityProviderSettingsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Attr) {
		toSerialize["attr"] = o.Attr
	}
	return toSerialize, nil
}

type NullableEditExternalIdentityProviderSettingsRequest struct {
	value *EditExternalIdentityProviderSettingsRequest
	isSet bool
}

func (v NullableEditExternalIdentityProviderSettingsRequest) Get() *EditExternalIdentityProviderSettingsRequest {
	return v.value
}

func (v *NullableEditExternalIdentityProviderSettingsRequest) Set(val *EditExternalIdentityProviderSettingsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEditExternalIdentityProviderSettingsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEditExternalIdentityProviderSettingsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditExternalIdentityProviderSettingsRequest(val *EditExternalIdentityProviderSettingsRequest) *NullableEditExternalIdentityProviderSettingsRequest {
	return &NullableEditExternalIdentityProviderSettingsRequest{value: val, isSet: true}
}

func (v NullableEditExternalIdentityProviderSettingsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditExternalIdentityProviderSettingsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


