/*
mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailcowsdk

import (
	"encoding/json"
)

// checks if the EditCrossOriginResourceSharingCORSSettingsRequestAttr type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditCrossOriginResourceSharingCORSSettingsRequestAttr{}

// EditCrossOriginResourceSharingCORSSettingsRequestAttr struct for EditCrossOriginResourceSharingCORSSettingsRequestAttr
type EditCrossOriginResourceSharingCORSSettingsRequestAttr struct {
	AllowedOrigins []string `json:"allowed_origins,omitempty"`
	AllowedMethods []string `json:"allowed_methods,omitempty"`
}

// NewEditCrossOriginResourceSharingCORSSettingsRequestAttr instantiates a new EditCrossOriginResourceSharingCORSSettingsRequestAttr object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditCrossOriginResourceSharingCORSSettingsRequestAttr() *EditCrossOriginResourceSharingCORSSettingsRequestAttr {
	this := EditCrossOriginResourceSharingCORSSettingsRequestAttr{}
	return &this
}

// NewEditCrossOriginResourceSharingCORSSettingsRequestAttrWithDefaults instantiates a new EditCrossOriginResourceSharingCORSSettingsRequestAttr object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditCrossOriginResourceSharingCORSSettingsRequestAttrWithDefaults() *EditCrossOriginResourceSharingCORSSettingsRequestAttr {
	this := EditCrossOriginResourceSharingCORSSettingsRequestAttr{}
	return &this
}

// GetAllowedOrigins returns the AllowedOrigins field value if set, zero value otherwise.
func (o *EditCrossOriginResourceSharingCORSSettingsRequestAttr) GetAllowedOrigins() []string {
	if o == nil || IsNil(o.AllowedOrigins) {
		var ret []string
		return ret
	}
	return o.AllowedOrigins
}

// GetAllowedOriginsOk returns a tuple with the AllowedOrigins field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditCrossOriginResourceSharingCORSSettingsRequestAttr) GetAllowedOriginsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedOrigins) {
		return nil, false
	}
	return o.AllowedOrigins, true
}

// HasAllowedOrigins returns a boolean if a field has been set.
func (o *EditCrossOriginResourceSharingCORSSettingsRequestAttr) HasAllowedOrigins() bool {
	if o != nil && !IsNil(o.AllowedOrigins) {
		return true
	}

	return false
}

// SetAllowedOrigins gets a reference to the given []string and assigns it to the AllowedOrigins field.
func (o *EditCrossOriginResourceSharingCORSSettingsRequestAttr) SetAllowedOrigins(v []string) {
	o.AllowedOrigins = v
}

// GetAllowedMethods returns the AllowedMethods field value if set, zero value otherwise.
func (o *EditCrossOriginResourceSharingCORSSettingsRequestAttr) GetAllowedMethods() []string {
	if o == nil || IsNil(o.AllowedMethods) {
		var ret []string
		return ret
	}
	return o.AllowedMethods
}

// GetAllowedMethodsOk returns a tuple with the AllowedMethods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditCrossOriginResourceSharingCORSSettingsRequestAttr) GetAllowedMethodsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedMethods) {
		return nil, false
	}
	return o.AllowedMethods, true
}

// HasAllowedMethods returns a boolean if a field has been set.
func (o *EditCrossOriginResourceSharingCORSSettingsRequestAttr) HasAllowedMethods() bool {
	if o != nil && !IsNil(o.AllowedMethods) {
		return true
	}

	return false
}

// SetAllowedMethods gets a reference to the given []string and assigns it to the AllowedMethods field.
func (o *EditCrossOriginResourceSharingCORSSettingsRequestAttr) SetAllowedMethods(v []string) {
	o.AllowedMethods = v
}

func (o EditCrossOriginResourceSharingCORSSettingsRequestAttr) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditCrossOriginResourceSharingCORSSettingsRequestAttr) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AllowedOrigins) {
		toSerialize["allowed_origins"] = o.AllowedOrigins
	}
	if !IsNil(o.AllowedMethods) {
		toSerialize["allowed_methods"] = o.AllowedMethods
	}
	return toSerialize, nil
}

type NullableEditCrossOriginResourceSharingCORSSettingsRequestAttr struct {
	value *EditCrossOriginResourceSharingCORSSettingsRequestAttr
	isSet bool
}

func (v NullableEditCrossOriginResourceSharingCORSSettingsRequestAttr) Get() *EditCrossOriginResourceSharingCORSSettingsRequestAttr {
	return v.value
}

func (v *NullableEditCrossOriginResourceSharingCORSSettingsRequestAttr) Set(val *EditCrossOriginResourceSharingCORSSettingsRequestAttr) {
	v.value = val
	v.isSet = true
}

func (v NullableEditCrossOriginResourceSharingCORSSettingsRequestAttr) IsSet() bool {
	return v.isSet
}

func (v *NullableEditCrossOriginResourceSharingCORSSettingsRequestAttr) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditCrossOriginResourceSharingCORSSettingsRequestAttr(val *EditCrossOriginResourceSharingCORSSettingsRequestAttr) *NullableEditCrossOriginResourceSharingCORSSettingsRequestAttr {
	return &NullableEditCrossOriginResourceSharingCORSSettingsRequestAttr{value: val, isSet: true}
}

func (v NullableEditCrossOriginResourceSharingCORSSettingsRequestAttr) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditCrossOriginResourceSharingCORSSettingsRequestAttr) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


