/*
mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailcowsdk

import (
	"encoding/json"
)

// checks if the EditExternalIdentityProviderSettingsRequestAttr type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditExternalIdentityProviderSettingsRequestAttr{}

// EditExternalIdentityProviderSettingsRequestAttr struct for EditExternalIdentityProviderSettingsRequestAttr
type EditExternalIdentityProviderSettingsRequestAttr struct {
	// Specifies the type of the Identity Provider
	Authsource *string `json:"authsource,omitempty"`
	// The base URL of your Keycloak server. Required if `authsource` is keycloak.
	ServerUrl *string `json:"server_url,omitempty"`
	// The Keycloak realm where the mailcow client is configured. Required if `authsource` is keycloak.
	Realm *string `json:"realm,omitempty"`
	// The Client ID assigned to mailcow Client in OIDC Provider. Required if `authsource` is keycloak or generic-oidc.
	ClientId *string `json:"client_id,omitempty"`
	// The Client Secret assigned to mailcow Client in OIDC Provider. Required if `authsource` is keycloak or generic-oidc.
	ClientSecret *string `json:"client_secret,omitempty"`
	// The redirect URL that OIDC Provider will use after authentication. Required if `authsource` is keycloak or generic-oidc.
	RedirectUrl *string `json:"redirect_url,omitempty"`
	// Additional redirect URLs that OIDC Provider can use after authentication if valid.
	RedirectUrlExtra []interface{} `json:"redirect_url_extra,omitempty"`
	// Specifies the Keycloak version. Required if `authsource` is keycloak.
	Version *string `json:"version,omitempty"`
	// (Optional) If no matching Attribute Mapping exists for a User, the default template will be used for creating the mailbox, but not for updating the mailbox.
	DefaultTemplate *string `json:"default_template,omitempty"`
	// (Optional) Attribute values used to match a mailbox template. Each element corresponds to the respective index in the templates array (i.e., the first element matches the first element of templates, the second matches the second, and so on).
	Mappers []interface{} `json:"mappers,omitempty"`
	// (Optional) Defines the mailbox templates to be assigned. Each element corresponds to the respective index in the `mappers` array.
	Templates []interface{} `json:"templates,omitempty"`
	// If enabled, SSL certificate validation is bypassed
	IgnoreSslError *bool `json:"ignore_ssl_error,omitempty"`
	// If enabled, mailcow will attempt to validate user credentials using the Keycloak Admin REST API instead of relying solely on the Authorization Code Flow.
	MailpasswordFlow *bool `json:"mailpassword_flow,omitempty"`
	// If enabled, mailcow periodically performs a full sync of all users from Keycloak or LDAP.
	PeriodicSync *bool `json:"periodic_sync,omitempty"`
	// If enabled, new users are automatically imported from Keycloak or LDAP into mailcow.
	ImportUsers *bool `json:"import_users,omitempty"`
	// Defines the time interval (in minutes) for periodic synchronization and user imports.
	SyncInterval *float32 `json:"sync_interval,omitempty"`
	// The address of your LDAP server. You can provide a single hostname or a comma-separated list of hosts for fallback in case the primary server is unreachable. Required if `authsource` is ldap.
	Host *string `json:"host,omitempty"`
	// The port used to connect to the LDAP server. Required if `authsource` is ldap.
	Port *string `json:"port,omitempty"`
	// enable LDAPS connection. If Port is set to 389 it will be overriden to 636.
	UseSsl *bool `json:"use_ssl,omitempty"`
	// enable TLS connection. TLS is recommended over SSL. SSL Ports cannot be used.
	UseTls *bool `json:"use_tls,omitempty"`
	// The Distinguished Name (DN) from which searches will be performed. Required if `authsource` is ldap.
	Basedn *string `json:"basedn,omitempty"`
	// The LDAP attribute used to identify users during authentication. Required if `authsource` is ldap.
	UsernameField *string `json:"username_field,omitempty"`
	// An optional LDAP search filter to refine which users can authenticate.
	Filter *string `json:"filter,omitempty"`
	// Specifies an LDAP attribute that holds a specific value which can be mapped to a mailbox template using the Attribute Mapping section. Required if `authsource` is ldap.
	AttributeField *string `json:"attribute_field,omitempty"`
	// The Distinguished Name (DN) of the LDAP user that will be used to authenticate and perform LDAP searches. This account should have sufficient permissions to read the required attributes. Required if `authsource` is ldap.
	Binddn *string `json:"binddn,omitempty"`
	// The password for the Bind DN user. It is required for authentication when connecting to the LDAP server. Required if `authsource` is ldap.
	Bindpass *string `json:"bindpass,omitempty"`
	// The OIDC provider's authorization server URL. Required if `authsource` is generic-oidc.
	AuthorizeUrl *string `json:"authorize_url,omitempty"`
	// The OIDC provider's token server URL. Required if `authsource` is generic-oidc.
	TokenUrl *string `json:"token_url,omitempty"`
	// The OIDC provider's user info server URL. Required if `authsource` is generic-oidc.
	UserinfoUrl *string `json:"userinfo_url,omitempty"`
	// Specifies the OIDC scopes requested during authentication.
	ClientScopes *string `json:"client_scopes,omitempty"`
}

// NewEditExternalIdentityProviderSettingsRequestAttr instantiates a new EditExternalIdentityProviderSettingsRequestAttr object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditExternalIdentityProviderSettingsRequestAttr() *EditExternalIdentityProviderSettingsRequestAttr {
	this := EditExternalIdentityProviderSettingsRequestAttr{}
	var ignoreSslError bool = false
	this.IgnoreSslError = &ignoreSslError
	var mailpasswordFlow bool = false
	this.MailpasswordFlow = &mailpasswordFlow
	var periodicSync bool = false
	this.PeriodicSync = &periodicSync
	var importUsers bool = false
	this.ImportUsers = &importUsers
	var syncInterval float32 = 15
	this.SyncInterval = &syncInterval
	var useSsl bool = false
	this.UseSsl = &useSsl
	var useTls bool = false
	this.UseTls = &useTls
	var usernameField string = "mail"
	this.UsernameField = &usernameField
	var clientScopes string = "openid profile email mailcow_template"
	this.ClientScopes = &clientScopes
	return &this
}

// NewEditExternalIdentityProviderSettingsRequestAttrWithDefaults instantiates a new EditExternalIdentityProviderSettingsRequestAttr object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditExternalIdentityProviderSettingsRequestAttrWithDefaults() *EditExternalIdentityProviderSettingsRequestAttr {
	this := EditExternalIdentityProviderSettingsRequestAttr{}
	var ignoreSslError bool = false
	this.IgnoreSslError = &ignoreSslError
	var mailpasswordFlow bool = false
	this.MailpasswordFlow = &mailpasswordFlow
	var periodicSync bool = false
	this.PeriodicSync = &periodicSync
	var importUsers bool = false
	this.ImportUsers = &importUsers
	var syncInterval float32 = 15
	this.SyncInterval = &syncInterval
	var useSsl bool = false
	this.UseSsl = &useSsl
	var useTls bool = false
	this.UseTls = &useTls
	var usernameField string = "mail"
	this.UsernameField = &usernameField
	var clientScopes string = "openid profile email mailcow_template"
	this.ClientScopes = &clientScopes
	return &this
}

// GetAuthsource returns the Authsource field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetAuthsource() string {
	if o == nil || IsNil(o.Authsource) {
		var ret string
		return ret
	}
	return *o.Authsource
}

// GetAuthsourceOk returns a tuple with the Authsource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetAuthsourceOk() (*string, bool) {
	if o == nil || IsNil(o.Authsource) {
		return nil, false
	}
	return o.Authsource, true
}

// HasAuthsource returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasAuthsource() bool {
	if o != nil && !IsNil(o.Authsource) {
		return true
	}

	return false
}

// SetAuthsource gets a reference to the given string and assigns it to the Authsource field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetAuthsource(v string) {
	o.Authsource = &v
}

// GetServerUrl returns the ServerUrl field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetServerUrl() string {
	if o == nil || IsNil(o.ServerUrl) {
		var ret string
		return ret
	}
	return *o.ServerUrl
}

// GetServerUrlOk returns a tuple with the ServerUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetServerUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ServerUrl) {
		return nil, false
	}
	return o.ServerUrl, true
}

// HasServerUrl returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasServerUrl() bool {
	if o != nil && !IsNil(o.ServerUrl) {
		return true
	}

	return false
}

// SetServerUrl gets a reference to the given string and assigns it to the ServerUrl field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetServerUrl(v string) {
	o.ServerUrl = &v
}

// GetRealm returns the Realm field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetRealm() string {
	if o == nil || IsNil(o.Realm) {
		var ret string
		return ret
	}
	return *o.Realm
}

// GetRealmOk returns a tuple with the Realm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetRealmOk() (*string, bool) {
	if o == nil || IsNil(o.Realm) {
		return nil, false
	}
	return o.Realm, true
}

// HasRealm returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasRealm() bool {
	if o != nil && !IsNil(o.Realm) {
		return true
	}

	return false
}

// SetRealm gets a reference to the given string and assigns it to the Realm field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetRealm(v string) {
	o.Realm = &v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetClientId(v string) {
	o.ClientId = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetClientSecret() string {
	if o == nil || IsNil(o.ClientSecret) {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetClientSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ClientSecret) {
		return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasClientSecret() bool {
	if o != nil && !IsNil(o.ClientSecret) {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetClientSecret(v string) {
	o.ClientSecret = &v
}

// GetRedirectUrl returns the RedirectUrl field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetRedirectUrl() string {
	if o == nil || IsNil(o.RedirectUrl) {
		var ret string
		return ret
	}
	return *o.RedirectUrl
}

// GetRedirectUrlOk returns a tuple with the RedirectUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetRedirectUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RedirectUrl) {
		return nil, false
	}
	return o.RedirectUrl, true
}

// HasRedirectUrl returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasRedirectUrl() bool {
	if o != nil && !IsNil(o.RedirectUrl) {
		return true
	}

	return false
}

// SetRedirectUrl gets a reference to the given string and assigns it to the RedirectUrl field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetRedirectUrl(v string) {
	o.RedirectUrl = &v
}

// GetRedirectUrlExtra returns the RedirectUrlExtra field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetRedirectUrlExtra() []interface{} {
	if o == nil || IsNil(o.RedirectUrlExtra) {
		var ret []interface{}
		return ret
	}
	return o.RedirectUrlExtra
}

// GetRedirectUrlExtraOk returns a tuple with the RedirectUrlExtra field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetRedirectUrlExtraOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.RedirectUrlExtra) {
		return nil, false
	}
	return o.RedirectUrlExtra, true
}

// HasRedirectUrlExtra returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasRedirectUrlExtra() bool {
	if o != nil && !IsNil(o.RedirectUrlExtra) {
		return true
	}

	return false
}

// SetRedirectUrlExtra gets a reference to the given []interface{} and assigns it to the RedirectUrlExtra field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetRedirectUrlExtra(v []interface{}) {
	o.RedirectUrlExtra = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetVersion(v string) {
	o.Version = &v
}

// GetDefaultTemplate returns the DefaultTemplate field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetDefaultTemplate() string {
	if o == nil || IsNil(o.DefaultTemplate) {
		var ret string
		return ret
	}
	return *o.DefaultTemplate
}

// GetDefaultTemplateOk returns a tuple with the DefaultTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetDefaultTemplateOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultTemplate) {
		return nil, false
	}
	return o.DefaultTemplate, true
}

// HasDefaultTemplate returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasDefaultTemplate() bool {
	if o != nil && !IsNil(o.DefaultTemplate) {
		return true
	}

	return false
}

// SetDefaultTemplate gets a reference to the given string and assigns it to the DefaultTemplate field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetDefaultTemplate(v string) {
	o.DefaultTemplate = &v
}

// GetMappers returns the Mappers field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetMappers() []interface{} {
	if o == nil || IsNil(o.Mappers) {
		var ret []interface{}
		return ret
	}
	return o.Mappers
}

// GetMappersOk returns a tuple with the Mappers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetMappersOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Mappers) {
		return nil, false
	}
	return o.Mappers, true
}

// HasMappers returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasMappers() bool {
	if o != nil && !IsNil(o.Mappers) {
		return true
	}

	return false
}

// SetMappers gets a reference to the given []interface{} and assigns it to the Mappers field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetMappers(v []interface{}) {
	o.Mappers = v
}

// GetTemplates returns the Templates field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetTemplates() []interface{} {
	if o == nil || IsNil(o.Templates) {
		var ret []interface{}
		return ret
	}
	return o.Templates
}

// GetTemplatesOk returns a tuple with the Templates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetTemplatesOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Templates) {
		return nil, false
	}
	return o.Templates, true
}

// HasTemplates returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasTemplates() bool {
	if o != nil && !IsNil(o.Templates) {
		return true
	}

	return false
}

// SetTemplates gets a reference to the given []interface{} and assigns it to the Templates field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetTemplates(v []interface{}) {
	o.Templates = v
}

// GetIgnoreSslError returns the IgnoreSslError field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetIgnoreSslError() bool {
	if o == nil || IsNil(o.IgnoreSslError) {
		var ret bool
		return ret
	}
	return *o.IgnoreSslError
}

// GetIgnoreSslErrorOk returns a tuple with the IgnoreSslError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetIgnoreSslErrorOk() (*bool, bool) {
	if o == nil || IsNil(o.IgnoreSslError) {
		return nil, false
	}
	return o.IgnoreSslError, true
}

// HasIgnoreSslError returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasIgnoreSslError() bool {
	if o != nil && !IsNil(o.IgnoreSslError) {
		return true
	}

	return false
}

// SetIgnoreSslError gets a reference to the given bool and assigns it to the IgnoreSslError field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetIgnoreSslError(v bool) {
	o.IgnoreSslError = &v
}

// GetMailpasswordFlow returns the MailpasswordFlow field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetMailpasswordFlow() bool {
	if o == nil || IsNil(o.MailpasswordFlow) {
		var ret bool
		return ret
	}
	return *o.MailpasswordFlow
}

// GetMailpasswordFlowOk returns a tuple with the MailpasswordFlow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetMailpasswordFlowOk() (*bool, bool) {
	if o == nil || IsNil(o.MailpasswordFlow) {
		return nil, false
	}
	return o.MailpasswordFlow, true
}

// HasMailpasswordFlow returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasMailpasswordFlow() bool {
	if o != nil && !IsNil(o.MailpasswordFlow) {
		return true
	}

	return false
}

// SetMailpasswordFlow gets a reference to the given bool and assigns it to the MailpasswordFlow field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetMailpasswordFlow(v bool) {
	o.MailpasswordFlow = &v
}

// GetPeriodicSync returns the PeriodicSync field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetPeriodicSync() bool {
	if o == nil || IsNil(o.PeriodicSync) {
		var ret bool
		return ret
	}
	return *o.PeriodicSync
}

// GetPeriodicSyncOk returns a tuple with the PeriodicSync field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetPeriodicSyncOk() (*bool, bool) {
	if o == nil || IsNil(o.PeriodicSync) {
		return nil, false
	}
	return o.PeriodicSync, true
}

// HasPeriodicSync returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasPeriodicSync() bool {
	if o != nil && !IsNil(o.PeriodicSync) {
		return true
	}

	return false
}

// SetPeriodicSync gets a reference to the given bool and assigns it to the PeriodicSync field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetPeriodicSync(v bool) {
	o.PeriodicSync = &v
}

// GetImportUsers returns the ImportUsers field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetImportUsers() bool {
	if o == nil || IsNil(o.ImportUsers) {
		var ret bool
		return ret
	}
	return *o.ImportUsers
}

// GetImportUsersOk returns a tuple with the ImportUsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetImportUsersOk() (*bool, bool) {
	if o == nil || IsNil(o.ImportUsers) {
		return nil, false
	}
	return o.ImportUsers, true
}

// HasImportUsers returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasImportUsers() bool {
	if o != nil && !IsNil(o.ImportUsers) {
		return true
	}

	return false
}

// SetImportUsers gets a reference to the given bool and assigns it to the ImportUsers field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetImportUsers(v bool) {
	o.ImportUsers = &v
}

// GetSyncInterval returns the SyncInterval field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetSyncInterval() float32 {
	if o == nil || IsNil(o.SyncInterval) {
		var ret float32
		return ret
	}
	return *o.SyncInterval
}

// GetSyncIntervalOk returns a tuple with the SyncInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetSyncIntervalOk() (*float32, bool) {
	if o == nil || IsNil(o.SyncInterval) {
		return nil, false
	}
	return o.SyncInterval, true
}

// HasSyncInterval returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasSyncInterval() bool {
	if o != nil && !IsNil(o.SyncInterval) {
		return true
	}

	return false
}

// SetSyncInterval gets a reference to the given float32 and assigns it to the SyncInterval field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetSyncInterval(v float32) {
	o.SyncInterval = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetHost(v string) {
	o.Host = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetPort() string {
	if o == nil || IsNil(o.Port) {
		var ret string
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetPortOk() (*string, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given string and assigns it to the Port field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetPort(v string) {
	o.Port = &v
}

// GetUseSsl returns the UseSsl field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetUseSsl() bool {
	if o == nil || IsNil(o.UseSsl) {
		var ret bool
		return ret
	}
	return *o.UseSsl
}

// GetUseSslOk returns a tuple with the UseSsl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetUseSslOk() (*bool, bool) {
	if o == nil || IsNil(o.UseSsl) {
		return nil, false
	}
	return o.UseSsl, true
}

// HasUseSsl returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasUseSsl() bool {
	if o != nil && !IsNil(o.UseSsl) {
		return true
	}

	return false
}

// SetUseSsl gets a reference to the given bool and assigns it to the UseSsl field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetUseSsl(v bool) {
	o.UseSsl = &v
}

// GetUseTls returns the UseTls field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetUseTls() bool {
	if o == nil || IsNil(o.UseTls) {
		var ret bool
		return ret
	}
	return *o.UseTls
}

// GetUseTlsOk returns a tuple with the UseTls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetUseTlsOk() (*bool, bool) {
	if o == nil || IsNil(o.UseTls) {
		return nil, false
	}
	return o.UseTls, true
}

// HasUseTls returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasUseTls() bool {
	if o != nil && !IsNil(o.UseTls) {
		return true
	}

	return false
}

// SetUseTls gets a reference to the given bool and assigns it to the UseTls field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetUseTls(v bool) {
	o.UseTls = &v
}

// GetBasedn returns the Basedn field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetBasedn() string {
	if o == nil || IsNil(o.Basedn) {
		var ret string
		return ret
	}
	return *o.Basedn
}

// GetBasednOk returns a tuple with the Basedn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetBasednOk() (*string, bool) {
	if o == nil || IsNil(o.Basedn) {
		return nil, false
	}
	return o.Basedn, true
}

// HasBasedn returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasBasedn() bool {
	if o != nil && !IsNil(o.Basedn) {
		return true
	}

	return false
}

// SetBasedn gets a reference to the given string and assigns it to the Basedn field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetBasedn(v string) {
	o.Basedn = &v
}

// GetUsernameField returns the UsernameField field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetUsernameField() string {
	if o == nil || IsNil(o.UsernameField) {
		var ret string
		return ret
	}
	return *o.UsernameField
}

// GetUsernameFieldOk returns a tuple with the UsernameField field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetUsernameFieldOk() (*string, bool) {
	if o == nil || IsNil(o.UsernameField) {
		return nil, false
	}
	return o.UsernameField, true
}

// HasUsernameField returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasUsernameField() bool {
	if o != nil && !IsNil(o.UsernameField) {
		return true
	}

	return false
}

// SetUsernameField gets a reference to the given string and assigns it to the UsernameField field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetUsernameField(v string) {
	o.UsernameField = &v
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetFilter() string {
	if o == nil || IsNil(o.Filter) {
		var ret string
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetFilterOk() (*string, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given string and assigns it to the Filter field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetFilter(v string) {
	o.Filter = &v
}

// GetAttributeField returns the AttributeField field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetAttributeField() string {
	if o == nil || IsNil(o.AttributeField) {
		var ret string
		return ret
	}
	return *o.AttributeField
}

// GetAttributeFieldOk returns a tuple with the AttributeField field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetAttributeFieldOk() (*string, bool) {
	if o == nil || IsNil(o.AttributeField) {
		return nil, false
	}
	return o.AttributeField, true
}

// HasAttributeField returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasAttributeField() bool {
	if o != nil && !IsNil(o.AttributeField) {
		return true
	}

	return false
}

// SetAttributeField gets a reference to the given string and assigns it to the AttributeField field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetAttributeField(v string) {
	o.AttributeField = &v
}

// GetBinddn returns the Binddn field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetBinddn() string {
	if o == nil || IsNil(o.Binddn) {
		var ret string
		return ret
	}
	return *o.Binddn
}

// GetBinddnOk returns a tuple with the Binddn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetBinddnOk() (*string, bool) {
	if o == nil || IsNil(o.Binddn) {
		return nil, false
	}
	return o.Binddn, true
}

// HasBinddn returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasBinddn() bool {
	if o != nil && !IsNil(o.Binddn) {
		return true
	}

	return false
}

// SetBinddn gets a reference to the given string and assigns it to the Binddn field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetBinddn(v string) {
	o.Binddn = &v
}

// GetBindpass returns the Bindpass field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetBindpass() string {
	if o == nil || IsNil(o.Bindpass) {
		var ret string
		return ret
	}
	return *o.Bindpass
}

// GetBindpassOk returns a tuple with the Bindpass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetBindpassOk() (*string, bool) {
	if o == nil || IsNil(o.Bindpass) {
		return nil, false
	}
	return o.Bindpass, true
}

// HasBindpass returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasBindpass() bool {
	if o != nil && !IsNil(o.Bindpass) {
		return true
	}

	return false
}

// SetBindpass gets a reference to the given string and assigns it to the Bindpass field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetBindpass(v string) {
	o.Bindpass = &v
}

// GetAuthorizeUrl returns the AuthorizeUrl field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetAuthorizeUrl() string {
	if o == nil || IsNil(o.AuthorizeUrl) {
		var ret string
		return ret
	}
	return *o.AuthorizeUrl
}

// GetAuthorizeUrlOk returns a tuple with the AuthorizeUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetAuthorizeUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AuthorizeUrl) {
		return nil, false
	}
	return o.AuthorizeUrl, true
}

// HasAuthorizeUrl returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasAuthorizeUrl() bool {
	if o != nil && !IsNil(o.AuthorizeUrl) {
		return true
	}

	return false
}

// SetAuthorizeUrl gets a reference to the given string and assigns it to the AuthorizeUrl field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetAuthorizeUrl(v string) {
	o.AuthorizeUrl = &v
}

// GetTokenUrl returns the TokenUrl field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetTokenUrl() string {
	if o == nil || IsNil(o.TokenUrl) {
		var ret string
		return ret
	}
	return *o.TokenUrl
}

// GetTokenUrlOk returns a tuple with the TokenUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetTokenUrlOk() (*string, bool) {
	if o == nil || IsNil(o.TokenUrl) {
		return nil, false
	}
	return o.TokenUrl, true
}

// HasTokenUrl returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasTokenUrl() bool {
	if o != nil && !IsNil(o.TokenUrl) {
		return true
	}

	return false
}

// SetTokenUrl gets a reference to the given string and assigns it to the TokenUrl field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetTokenUrl(v string) {
	o.TokenUrl = &v
}

// GetUserinfoUrl returns the UserinfoUrl field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetUserinfoUrl() string {
	if o == nil || IsNil(o.UserinfoUrl) {
		var ret string
		return ret
	}
	return *o.UserinfoUrl
}

// GetUserinfoUrlOk returns a tuple with the UserinfoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetUserinfoUrlOk() (*string, bool) {
	if o == nil || IsNil(o.UserinfoUrl) {
		return nil, false
	}
	return o.UserinfoUrl, true
}

// HasUserinfoUrl returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasUserinfoUrl() bool {
	if o != nil && !IsNil(o.UserinfoUrl) {
		return true
	}

	return false
}

// SetUserinfoUrl gets a reference to the given string and assigns it to the UserinfoUrl field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetUserinfoUrl(v string) {
	o.UserinfoUrl = &v
}

// GetClientScopes returns the ClientScopes field value if set, zero value otherwise.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetClientScopes() string {
	if o == nil || IsNil(o.ClientScopes) {
		var ret string
		return ret
	}
	return *o.ClientScopes
}

// GetClientScopesOk returns a tuple with the ClientScopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) GetClientScopesOk() (*string, bool) {
	if o == nil || IsNil(o.ClientScopes) {
		return nil, false
	}
	return o.ClientScopes, true
}

// HasClientScopes returns a boolean if a field has been set.
func (o *EditExternalIdentityProviderSettingsRequestAttr) HasClientScopes() bool {
	if o != nil && !IsNil(o.ClientScopes) {
		return true
	}

	return false
}

// SetClientScopes gets a reference to the given string and assigns it to the ClientScopes field.
func (o *EditExternalIdentityProviderSettingsRequestAttr) SetClientScopes(v string) {
	o.ClientScopes = &v
}

func (o EditExternalIdentityProviderSettingsRequestAttr) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditExternalIdentityProviderSettingsRequestAttr) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Authsource) {
		toSerialize["authsource"] = o.Authsource
	}
	if !IsNil(o.ServerUrl) {
		toSerialize["server_url"] = o.ServerUrl
	}
	if !IsNil(o.Realm) {
		toSerialize["realm"] = o.Realm
	}
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.ClientSecret) {
		toSerialize["client_secret"] = o.ClientSecret
	}
	if !IsNil(o.RedirectUrl) {
		toSerialize["redirect_url"] = o.RedirectUrl
	}
	if !IsNil(o.RedirectUrlExtra) {
		toSerialize["redirect_url_extra"] = o.RedirectUrlExtra
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.DefaultTemplate) {
		toSerialize["default_template"] = o.DefaultTemplate
	}
	if !IsNil(o.Mappers) {
		toSerialize["mappers"] = o.Mappers
	}
	if !IsNil(o.Templates) {
		toSerialize["templates"] = o.Templates
	}
	if !IsNil(o.IgnoreSslError) {
		toSerialize["ignore_ssl_error"] = o.IgnoreSslError
	}
	if !IsNil(o.MailpasswordFlow) {
		toSerialize["mailpassword_flow"] = o.MailpasswordFlow
	}
	if !IsNil(o.PeriodicSync) {
		toSerialize["periodic_sync"] = o.PeriodicSync
	}
	if !IsNil(o.ImportUsers) {
		toSerialize["import_users"] = o.ImportUsers
	}
	if !IsNil(o.SyncInterval) {
		toSerialize["sync_interval"] = o.SyncInterval
	}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.UseSsl) {
		toSerialize["use_ssl"] = o.UseSsl
	}
	if !IsNil(o.UseTls) {
		toSerialize["use_tls"] = o.UseTls
	}
	if !IsNil(o.Basedn) {
		toSerialize["basedn"] = o.Basedn
	}
	if !IsNil(o.UsernameField) {
		toSerialize["username_field"] = o.UsernameField
	}
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	if !IsNil(o.AttributeField) {
		toSerialize["attribute_field"] = o.AttributeField
	}
	if !IsNil(o.Binddn) {
		toSerialize["binddn"] = o.Binddn
	}
	if !IsNil(o.Bindpass) {
		toSerialize["bindpass"] = o.Bindpass
	}
	if !IsNil(o.AuthorizeUrl) {
		toSerialize["authorize_url"] = o.AuthorizeUrl
	}
	if !IsNil(o.TokenUrl) {
		toSerialize["token_url"] = o.TokenUrl
	}
	if !IsNil(o.UserinfoUrl) {
		toSerialize["userinfo_url"] = o.UserinfoUrl
	}
	if !IsNil(o.ClientScopes) {
		toSerialize["client_scopes"] = o.ClientScopes
	}
	return toSerialize, nil
}

type NullableEditExternalIdentityProviderSettingsRequestAttr struct {
	value *EditExternalIdentityProviderSettingsRequestAttr
	isSet bool
}

func (v NullableEditExternalIdentityProviderSettingsRequestAttr) Get() *EditExternalIdentityProviderSettingsRequestAttr {
	return v.value
}

func (v *NullableEditExternalIdentityProviderSettingsRequestAttr) Set(val *EditExternalIdentityProviderSettingsRequestAttr) {
	v.value = val
	v.isSet = true
}

func (v NullableEditExternalIdentityProviderSettingsRequestAttr) IsSet() bool {
	return v.isSet
}

func (v *NullableEditExternalIdentityProviderSettingsRequestAttr) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditExternalIdentityProviderSettingsRequestAttr(val *EditExternalIdentityProviderSettingsRequestAttr) *NullableEditExternalIdentityProviderSettingsRequestAttr {
	return &NullableEditExternalIdentityProviderSettingsRequestAttr{value: val, isSet: true}
}

func (v NullableEditExternalIdentityProviderSettingsRequestAttr) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditExternalIdentityProviderSettingsRequestAttr) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


